### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by EpicEric** [dasniko/keycloak-user-spi-demo#1]
From [GitHub Help's topic](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository):

>[...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Could you clarify if me and others can use this code for our own projects?

**Comment by dasniko** [comment]
sorry, my fault, just added a license

but be aware, that the code is really just for demo cases, not reliable and already a few years old
